const mockServices = [{
    index: 1,
    id: '5ba1a747-0713-4b9d-809c-fa05ddca7bb5',
    categoryId: 'haircuts',
    imageUrl: "/images/manu/nail/pic1.jpg",
    title: "Deep Tissue Massage",
    featured: false,
    description: '60 – 100 Minute Session',
    price: 10
  },
  {
    index: 2,
    id: 'e7768bdb-1e22-4021-ba4e-916580c6e97e',
    categoryId: 'haircuts',
    imageUrl: "/images/manu/nail/pic2.jpg",
    title: "Swedish Massage",
    featured: false,
    description: '30 – 40 Minute Session',
    price: 10
  },
  {
    index: 3,
    id: '75bd3500-f5bb-4476-8acc-049f06404f7f',
    categoryId: 'haircuts',
    imageUrl: "/images/manu/nail/pic3.jpg",
    title: "Deep Tissue Massage",
    featured: false,
    description: '60 – 100 Minute Session',
    price: 20
  },
  {
    index: 4,
    id: 'b9887446-522b-41be-bb00-0baf662762af',
    categoryId: 'highlights',
    imageUrl: "/images/manu/nail/pic4.jpg",
    title: "Therapeutic Massage",
    featured: false,
    description: '60 – 100 Minute Session',
    price: 20
  },
  {
    index: 5,
    id: 'd72eee32-5b92-4f70-af79-bd9c95ed82f1',
    categoryId: 'massage',
    imageUrl: "/images/manu/nail/pic5.jpg",
    title: "Hot Stone Massage",
    featured: false,
    description: '50 – 60 Minute Session',
    price: 20
  },
  {
    index: 6,
    id: '6f121331-e17b-4124-89c8-6f2f73d4ae47',
    categoryId: 'massage',
    imageUrl: "/images/manu/nail/pic6.jpg",
    title: "Couples Massage",
    featured: false,
    description: '20 - 30 Minute Session',
    price: 25
  },
  {
    index: 7,
    id: 'c390f2a7-cd0e-4540-aa91-fdbc6f9efb42',
    categoryId: 'highlights',
    imageUrl: "/images/manu/nail/pic1.jpg",
    title: "Facial",
    featured: false,
    description: '15 - 30 Minute Session',
    price: 30
  },
  {
    index: 8,
    id: 'fa4cdb3e-3c53-42cb-9777-a55af46b62ed',
    categoryId: 'coloring',
    imageUrl: "/images/manu/nail/pic2.jpg",
    title: "Body Waxing",
    featured: false,
    description: '80 – 100 Minute Session',
    price: 30
  },
  {
    index: 9,
    id: '684ef6b3-ec8c-4483-a3d3-446751b1262b',
    categoryId: 'coloring',
    imageUrl: "/images/manu/nail/pic3.jpg",
    title: "Deep Tissue Massage",
    featured: false,
    description: '60 – 100 Minute Session',
    price: 35
  },{
    index: 10,
    id: '624c1bec-f320-4bb7-b663-9ff909fa3110',
    categoryId: 'massage',
    imageUrl: "/images/manu/nail/pic4.jpg",
    title: "Therapeutic Massage",
    featured: false,
    description: '30 – 40 Minute Session',
    price: 35
  },
  {
    index: 11,
    id: '2a6a0585-7cdf-4fdf-b934-e0b2e3593e5c',
    categoryId: 'makeup',
    imageUrl: "/images/blog/grid/pic1.jpg",
    title: "Body Treatments",
    featured: false,
    description: "Lorem Ipsum is simply dummy text of the printing.",
    price: 40,
  },
  {
    index: 12,
    id:"30ab06d3-a172-4f93-a35d-1499d3ff58e2",
    categoryId: "makeup",
    imageUrl: "/images/blog/grid/pic2.jpg",
    title: "Massages",
    featured: false,
    description: "Lorem Ipsum is simply dummy text of the printing.",
    price: 45,
  },
  {
    index: 13,
    id:"ab70088d-20ed-4b9c-a4fe-16ad2217ea44",
    categoryId: "highlights",
    imageUrl: "/images/blog/grid/pic3.jpg",
    title: "Organic Kulk Service",
    featured: false,
    description: "Lorem Ipsum is simply dummy text of the printing.",
    price: 50,
  },
  {
    index: 14,
    id:"c4f89d05-10fd-4b01-884a-463b39e8b617",
    categoryId: "makeup",
    imageUrl: "/images/blog/grid/pic4.jpg",
    title: "Hair Makeup",
    featured: false,
    description: "Lorem Ipsum is simply dummy text of the printing.",
    price: 55,
  },
  {
    index: 15,
    id:"44e901c1-7281-4ede-85e6-fffa14230728",
    categoryId: "makeup",
    imageUrl: "/images/blog/grid/pic5.jpg",
    title: "Beauty & Clinic Service",
    featured: false,
    description: "Lorem Ipsum is simply dummy text of the printing.",
    price: 60,
  },
  {
    index: 16,
    id:"e66d0856-5a39-42de-8cf0-be6045cbc442",
    categoryId: "highlights",
    imageUrl: "/images/blog/grid/pic6.jpg",
    title: "Aromatherapy",
    featured: false,
    description: "Lorem Ipsum is simply dummy text of the printing.",
    price: 65,
  },
  {
    index: 17,
    id: 'c8879479-2f49-4816-a42f-e5098b1ecce6',
    categoryId: "highlights",
    imageUrl:"/images/our-services/pic6.jpg",
    title:"Glitter or Nail Art",
    featured: true,
    description:"There are many variations of passages of Lorem Ipsum available, but the majority.",
    price: 60,
},
{
    index: 18,
    id: 'a317be07-feed-4009-8b57-073214455543',
    categoryId: "massage",
    imageUrl:"/images/our-services/pic7.jpg",
    title:"Classic Pedicure",
    featured: true,
    description:"There are many variations of passages of Lorem Ipsum available, but the majority.",
    price: 60,
},
{
    index: 19,
    id: '381daf10-001e-4474-a4ce-cad3b7ea8bf7',
    categoryId: "coloring",
    imageUrl:"/images/our-services/pic8.jpg",
    title:"Paraffin Hands",
    featured: true,
    description:"There are many variations of passages of Lorem Ipsum available, but the majority.",
    price: 60,
},
]

const categories = [
      {
        index: 0,
        categoryId: "haircuts",
        icon: "flaticon-woman",
        title: "Body Treatments",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting has been the industry.",
    },
    {
        index: 1,
        categoryId: "coloring",
        icon: "flaticon-mortar",
        title: "Aromatherapy",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting has been the industry.",
    },
    {
        index: 2,
        categoryId: "makeup",
        icon: "flaticon-sauna-1",
        title: "Aromatherapy",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting has been the industry.",
    },
    {
        index: 3,
        categoryId: "massage",
        icon: "flaticon-barbershop",
        title: "Hair Makeup",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting has been the industry.",
    },
    {
        index: 4,
        categoryId: "highlights",
        icon: "flaticon-makeup-1",
        title: "Organic Kulk Service",
        description: "Lorem Ipsum is simply dummy text of the printing and typesetting has been the industry.",
    },
    ]

    export {mockServices, categories}